---
- name: How to output to the screen with debug
  hosts: localhost
  connection: localhost
  gather_facts: no

  vars:
    vendorip: '192.168.22.55'

  tasks:
  - name: Print out to the screen
    debug:
      msg: "Welcome to Ansible"

  - name: Print out to the screen
    debug:
      msg: "The vendor IP is {{vendorip}}"

  - name: Print a message variable
    debug:
      var: vendorip
    
  - name: Print only with verbosity
    ansible.builtin.debug:
      var: vendorip
      verbosity: 2
