---
- name: Playbook - Install figlet
  hosts: planetexpress #removes farnsworth from the planet express group
  connection: ssh
  gather_facts: yes 

  tasks:
  - name: using apt to install figlet
    ansible.builtin.apt: #runs apt.py
        name: figlet
        state: present
    become: yes